server:
  port: 9003
spring:
  application:
    name: eureka-client
eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:18761/eureka/
